Deploy new
helphubteam/helphub pull request #122
Opened 2022-03-07 07:12 UTC by tsaregor

update ci to new server

2022-03-08 11:57 UTC, lxkuz requested changes

2022-03-08 11:57 UTC, lxkuz commented on .github/workflows/deploy_staging_new.yml
> +      - deploy_new
@tsaregor  давай уберем ее

2022-03-08 11:58 UTC, tsaregor commented on .github/workflows/deploy_staging_new.yml
> +      - deploy_new
давай

2022-03-08 12:21 UTC, memumen commented on .github/workflows/deploy_staging_new.yml
> +      WEBAPP_IMAGE: 886471362192.dkr.ecr.eu-central-1.amazonaws.com/production
Я думаю лучше разделить имиджи и для стейджинга использовать другой репозиторий

2022-03-12 09:24 UTC, tsaregor commented on .github/workflows/deploy_staging_new.yml
> +      WEBAPP_IMAGE: 886471362192.dkr.ecr.eu-central-1.amazonaws.com/production
да можно, только пушить в другие репозитории (не /production) не получается, так как нет прав

2022-03-17 05:20 UTC, memumen commented on .github/workflows/deploy_staging_new.yml
> +      WEBAPP_IMAGE: 886471362192.dkr.ecr.eu-central-1.amazonaws.com/production
@tsaregor пробуй `886471362192.dkr.ecr.eu-central-1.amazonaws.com/staging`

2022-03-19 10:22 UTC, tsaregor commented on .github/workflows/deploy_staging_new.yml
> +      WEBAPP_IMAGE: 886471362192.dkr.ecr.eu-central-1.amazonaws.com/production
попробовал, [закоммитил](https://github.com/helphubteam/helphub/commit/eed511857e13ea7209af16ef03ca366a83ac8e29)).

[Пайплайн](https://github.com/helphubteam/helphub/actions/runs/2008299756) валится на пуше в докер реджистри

2022-04-11 05:34 UTC, lxkuz approved these changes

2022-04-11 05:35 UTC, merged

2022-04-11 05:35 UTC, lxkuz commented
1) убрал deploy_new ветку
2) оставил production docker image